### PR TITLE
Do not use CheckAndRaise c_code for non-dense inputs

### PR DESCRIPTION
**Pull request by ricardoV94**
This would fail not only with `Sparse` (as mentioned in #885) but also `Scalar` types

```python
import aesara.scalar
from aesara.raise_op import assert_op
x = aesara.scalar.float64("x")
a = assert_op(x, x>0)

(a + 1).eval({x: 1})
# CompileError: Compilation failed (return status=1):
# error: invalid cast from type ‘npy_float64’ {aka ‘double’} to type ‘PyObject*’ {aka ‘_object*’}
```

### CODE REVIEW

**Review by brandonwillard — COMMENTED** [review]
This could use a test; otherwise, looks good.

**Comment by ricardoV94** [comment]
Added a test with SparseVariables
